use_frameworks!

platform :ios, '9.0'


def dependencyFun
  pod 'FMDB/SQLCipher', '~> 2.7.5'
end

target 'EncryptedDB_Example' do
  pod 'EncryptedDB', :path => '../'
  dependencyFun
end


target 'EncryptedDB' do
  dependencyFun
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
 target.build_configurations.each do |config|
  if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
   end
  end
 end
end
