use_frameworks!

platform :ios, '9.0'


def dependencyFun
  pod 'FMDB/SQLCipher', '~> 2.7.5'
end

target 'EncryptedDB_Example' do
  pod 'EncryptedDB', :path => '../'
  dependencyFun
end


target 'EncryptedDB' do
  dependencyFun
end
